import { AlertCircle, FileOutput, Loader2 } from "lucide-react";
import { useState } from "react";
import { Button } from "../common/Button";
import { DeliverableCard } from "../deliverables/DeliverableCard";
import { executeTool } from "../../services/api/client";
import type { ChatMessage, Deliverable } from "../../types";

/** Phase I: turns one orchestrator response into a real, downloadable
 * report file via the backend's `report_generation` tool — reusing the
 * same `DeliverableCard` a Document Agent deliverable would render.
 */
export function GenerateReportButton({ message }: { message: ChatMessage }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [deliverable, setDeliverable] = useState<Deliverable | null>(null);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await executeTool("report_generation", {
        title: "Security Assessment Report",
        task: "Assess system security status and identify anything unusual.",
        data_sources: ["Local system", "Local network", "Local knowledge base"],
        findings: message.text ?? message.content?.map((b) => (b.type === "text" ? b.text : "")).join("\n") ?? "",
        ai_analysis: "See findings above — generated by the local model from observed system/network/policy data.",
        citations: [...new Set((message.citations ?? []).map((c) => c.label))],
        sovereignty_status: "LOCAL — no data or model prompt left this machine.",
        format: "md",
      });
      if (!result.success || !result.output) throw new Error(result.error ?? "Report generation failed.");
      const output = result.output as { filename: string; file_type: string; size_bytes: number; created_at: string };
      setDeliverable({
        id: output.filename,
        filename: output.filename,
        fileType: output.file_type,
        sizeBytes: output.size_bytes,
        status: "ready",
        createdAt: output.created_at,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Report generation failed.");
    } finally {
      setLoading(false);
    }
  };

  if (deliverable) return <DeliverableCard deliverable={deliverable} />;

  return (
    <div>
      <Button size="sm" variant="secondary" onClick={handleGenerate} disabled={loading}>
        {loading ? <Loader2 className="size-3.5 animate-spin" aria-hidden="true" /> : <FileOutput className="size-3.5" aria-hidden="true" />}
        Generate Report
      </Button>
      {error && (
        <p className="mt-1.5 flex items-center gap-1.5 text-xs text-danger-500">
          <AlertCircle className="size-3.5 shrink-0" aria-hidden="true" />
          {error}
        </p>
      )}
    </div>
  );
}
