"""Development local model provider.

Returns structured, clearly-labeled mock text instead of running real
inference. This exists so the full Agent → Router → Provider → Response
pipeline can be built, exercised, and tested before any model weights are
installed on the hardware described in `models/README.md`.

Swapping this for a real local runtime (Ollama, llama.cpp, vLLM, ...) later
means writing another `BaseModelProvider` implementation — the Agent API
and `ModelRouter` do not change.
"""

from __future__ import annotations

import asyncio
import time
from collections.abc import AsyncIterator

from app.models.base import BaseModelProvider, GenerationResult, ModelInfo, ProviderHealth

# No real inference happens here — this keeps latency visible in the UI
# without pretending a multi-second model load occurred.
_MOCK_LATENCY_SECONDS = 0.05


class LocalModelProvider(BaseModelProvider):
    """Mock local inference provider. No model weights are loaded."""

    name = "local"

    async def generate(
        self, *, model: ModelInfo, prompt: str, images: list[bytes] | None = None
    ) -> GenerationResult:
        # `images` is accepted for interface parity with `BaseModelProvider`
        # but intentionally unused: this is a text-only mock, and Vision
        # Agent only ever reaches here when no real vision provider is
        # registered — never claiming image understanding it didn't do.
        started = time.perf_counter()
        await asyncio.sleep(_MOCK_LATENCY_SECONDS)

        excerpt = prompt.strip().replace("\n", " ")
        if len(excerpt) > 160:
            excerpt = excerpt[:160] + "…"

        text = (
            f"[development mock output from `{model.id}`]\n\n"
            f"No local model runtime is connected yet — this text is generated by "
            f"`LocalModelProvider`, a placeholder that stands in for a real inference "
            f"backend (Ollama, llama.cpp, vLLM, ...). It received this prompt:\n\n"
            f"> {excerpt}"
        )

        return GenerationResult(
            text=text,
            model_id=model.id,
            is_mock=True,
            latency_ms=(time.perf_counter() - started) * 1000,
        )

    async def stream(self, *, model: ModelInfo, prompt: str) -> AsyncIterator[str]:
        result = await self.generate(model=model, prompt=prompt)
        for chunk in result.text.split(" "):
            await asyncio.sleep(0)
            yield chunk + " "

    async def health_check(self) -> ProviderHealth:
        return ProviderHealth(healthy=True, detail="mock provider — no external runtime required")
